### PR TITLE
Enhance the input validation to provide more specific error messages

### LINKED ISSUE #18: Improved Input Validation

### PR DESCRIPTION
**Pull request by Meetpidev**
- Enhance the input validation to provide more specific error messages and allow users to correct mistakes In Puzzle.
- User can Correct the input..

Screenshot 2024-10-23 181414

### CODE REVIEW

**Comment by Meetpidev** [comment]
@soni-shashan Please Review PR..

**Comment by soni-shashan** [comment]
### what if duplicate value added in row, column and box? when you print error mention which element is repeated

**Comment by Meetpidev** [comment]
@soni-shashan Updated PR.. Please Review It

**Comment by Meetpidev** [comment]
@soni-shashan  Updated Logic for duplicate value added in row, column and box with mentioned that which element is reapeated...

Screenshot 2024-10-23 200137

**Comment by soni-shashan** [comment]
closes #18

**Pull request merged**
